### This is a comment
POST http://localhost:3000/auth/register
Content-Type: application/json

{ "username": "melikaaa", "password": "1234" }

### Fetch User Profile
GET http://localhost:3000/api/users/67db6bb58d492bd01df92b3e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbGlrYWRhYiIsInVzZXJJZCI6IjY3ZGI2YmI1OGQ0OTJiZDAxZGY5MmIzZSIsImlhdCI6MTc0MjQzNDU3MywiZXhwIjoxNzQyNTIwOTczfQ.p3XNCx0swF-uDb0RMEcKlRbtuAgUIOJybXEt8H_Qpns

### Update User Profile
PUT http://localhost:3000/api/users/67db6bb58d492bd01df92b3e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbGlrYWRhYiIsInVzZXJJZCI6IjY3ZGI2YmI1OGQ0OTJiZDAxZGY5MmIzZSIsImlhdCI6MTc0MjQzNjI5OCwiZXhwIjoxNzQyNTIyNjk4fQ.I8MBDt0IA9hSzIiPKxZa-P-31N2CNAFl9rY0mMZyTlY
Content-Type: application/json

{
    "name": "Updated Name",
    "budget": "$9000",
    "location": "New Location",
    "interests": ["Updated Interest 1", "Updated Interest 2"]
}


### send match request
POST http://localhost:3000/api/users/67db6bb58d492bd01df92b3e/match
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbGlrYWRhYiIsInVzZXJJZCI6IjY3ZGI2YmI1OGQ0OTJiZDAxZGY5MmIzZSIsImlhdCI6MTc0MjQ0MjE4MSwiZXhwIjoxNzQyNTI4NTgxfQ.f3SkvwYGqCAitGYxbCb4lR_ZYjx697e85RJKC5LYSIw
Content-Type: application/json

{
  "matchId": "67da39f461ce575b37243676"
}

###
POST http://localhost:3000/auth/onboarding
Content-Type: application/json

{   "userId": "67da70cd46c8790c31a37237",
    "name": "Melika Dabiri",
    "budget": 1500,
    "location": "San Luis Obispo",
    "preferences": {
        "roomType": "Private",
        "smoking": false,
        "pets": true
    },
    "images": [],
    "interests": ["hiking", "coding", "music"]
}
### 
GET http://localhost:3000/api/images

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{ "username": "melika2", "password": "password" }

###
GET http://localhost:3000/api/images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbGlrYTIiLCJpYXQiOjE3NDE5NjM2OTIsImV4cCI6MTc0MjA1MDA5Mn0.4tUsphpZr5q6ZF4-RO5Ni9dOTjzQq-iO452ztQNcl4Y

###
GET http://localhost:3000/api/images

